image: gradle:alpine

stages:
 - jar

jar:
  stage: jar
  script:
    - ./gradlew build --configure-on-demand --no-daemon --parallel
  artifacts:
    expire_in: 1 week
    paths:
      - build/libs/*.jar