name: ScenarioManager
main: me.calebbassham.scenariomanager.plugin.ScenarioManagerPlugin
version: 0.2.2
author: Caleb Bassham
soft-depend: [Skript]

commands:
  scenariomanager:
    aliases: [scen, sm]